### ISSUE TITLE
About dataset and featurecluster

### ISSUE THREAD

**Issue by txw1997** [goldblum/FeatureClustering#1]
Hi, thanks for your excellent work!
I don't understand why you divide the dataset to four part?
And when compute the FC or HV loss, is we assume that we see c1, c2 as two class? But actually in  c1 or c2 include a lot of class.

**Comment by goldblum** [comment]
Hi!  We sample 2 images for each of 2 classes, hence why we divide the dataset into four parts.  When we compute FC and HV, we actually sample a large batch of class pairs with 4 images total in each class pair.  In order to vectorize the computation, we stack all the image1 from c1 into one tensor, image2 from c1 into one tensor, etc.  But different images in each stack may be from different classes since they are from different class pairs in the batch of class pairs.  Let me know if you have any other questions.
